---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: tags
  label: tags
- type: file
  name: intro_image
  label: intro_image
- type: text
  name: description
  label: description
